dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
 ]

linked_out/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import user_profile.urls as user_profile
import dashboard.urls as dashboard
import status.urls as status
import friend.urls as friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user_profile/', include(user_profile, namespace="user_profile")),
    url(r'^dashboard/', include(dashboard, namespace="dashboard")),
    url(r'^status/', include(status, namespace="status")),
    url(r'^friend/', include(friend, namespace="friend")),
]

status/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import index, add_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name = 'add_status'),
]

user_profile/urls.py
from django.conf.urls import url
from .views import index


#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
	url(r'^$', index, name='index'),

]

dashboard/models.py
from django.db import models

# Create your models here.

friend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
	name = models.CharField(max_length=27)
	url = models.URLField()
	created_date = models.DateTimeField(auto_now_add=True)

status/models.py
from django.db import models

class Update_Form(models.Model):
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

user_profile/models.py
from django.db import models
from datetime import date

DATE_INPUT_FORMATS = ('%d-%m-%Y')


# Create your models here.


class Person(models.Model):
    name = models.CharField(max_length=30)
    birthdate = models.DateField(default=date.today)
    gender = models.CharField(max_length=6)
    description = models.CharField(max_length=100)
    email = models.EmailField()

class Expertise(models.Model):
    expertise = models.CharField(max_length=255)

class PhotoURL(models.Model):
    model_pic = models.CharField(max_length=255)

friend/forms.py
from django import forms

class Add_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan URL',
    }
    name_attrs = {
        'type':'text',
    	'class':'form-control',
        'placeholder': 'Azmie'
    }
    url_attrs = {
        'type':'url',
    	'class':'form-control',
        'placeholder': 'https://google.com'
    }

    name = forms.CharField(label='Name', required=True, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='URL', required=True, widget=forms.TextInput(attrs=url_attrs))

status/forms.py
from django import forms

class Update_Bar(forms.Form):
    error_messages = {
        'required': 'Isi duls',
    }
    update_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 2,
        'class': 'update-textarea',
        'placeholder': 'sup?'
    }
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=update_attrs))

dashboard/views.py
from django.shortcuts import render
# TODO import status.models
# TODO import fiends.models
# TODO import user_profile.models

response = {}


def index(request):
    response["author"] = "Rayza"
    return render(request, 'dashboard/dashboard.html', response)

friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Form
from .models import Friend

# Create your views here.
response = {}

def index(request):
	friend = Friend.objects.all()
	response['friend'] = friend
	html = 'add_friend.html'
	response['add_form'] = Add_Form
	return render(request, html, response)

def add_friend(request):
	form = Add_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		friend = Friend(name=response['name'], url=response['url'])
		friend.save()
		return HttpResponseRedirect('/friend/')
	else:
		return HttpResponseRedirect('/friend/')

status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Update_Bar
from .models import Update_Form #di models namanya update

response = {}
def index(request):
    status = Update_Form.objects.all()
    response['status'] = status
    html = 'update_status/update_status.html'
    response['update_form'] = Update_Bar
    return render(request, html, response)

def add_status(request):
    form = Update_Bar(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Update_Form(description=response['description'])
        status.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

user_profile/views.py
from django.shortcuts import render
from .models import Person, Expertise, PhotoURL

# Create your views here.



def index(request):
    html = 'user_profile.html'
    person = Person.objects.all()

    person = Person.objects.create(name="Johann Sebastian Bach", birthdate="1685-03-31", gender="Male", description="Master of contrapuntal composition and professional harpsichord player", email="jsbach@gmail.com")
    expertise = Expertise.objects.create(expertise ="Contrapuntal composition")
    expertise = Expertise.objects.create(expertise ="Church leading musician")
    expertise = Expertise.objects.create(expertise ="Glorifying God")
    model_pic = expertise = PhotoURL.objects.create(model_pic ="http://www.bachsociety.org/wp-content/uploads/2017/01/Johann-sunglasses.jpg")

    response = {} #TODO Implement yourname
    response['author']= "Kezia Irene"
    response['name'] = Person.objects.all()[0].name
    response['birthdate'] = Person.objects.all()[0].birthdate
    response['gender'] = Person.objects.all()[0].gender
    response['expertise'] = Expertise.objects.all()[0:3]
    response['description'] = Person.objects.all()[0].description
    response['email'] = Person.objects.all()[0].email
    response['model_pic'] = PhotoURL.objects.all()[0].model_pic

    return render(request, html, response)

dashboard/templates/dashboard/dashboard.html
{% extends "layout/base.html" %}

{% block style %}
<!-- TODO -->
{% endblock %}

{% block title %}
Dashboard by {{ author }}
{% endblock %}

{% block content %}
<!-- TODO -->
{% endblock %}

friend/templates/add_friend.html
{% extends "layout/base.html" %}
{% block content %}
<section name='add-input' id='add-input'>
	<h4>Add Friend</h4>
	<form id='form' method="POST" action="{% url 'friend:add_friend' %}">
		{% csrf_token %}
        {{ add_form }}
        <br>
	    <button id="submit" type="submit" class="btn pull-right btn-primary">Add Friend</button>
	</form>
</section>
<section name='friend-list' id='friend-list'>
	<h4>List Friend</h4>
	<table class='table table-responsive table-hover'>
		<tbody>
			{% if friend %}
				{% for i in friend %}
				<tr>
					<td> {{ i.name }} </td>
					<td></td>
					<td> <a href="{{ i.url }}">{{ i.url }}</a> </td>
					<td> Added 	{{ i.created_date }} </td>
				</tr>
				{% endfor %}
			{% else %}
			<div class="alert alert-danger text-center">
                <strong>Oops!</strong> You don't have any friend :(.
            </div>
            {% endif %}
		</tbody>
	</table>
</section>
{% endblock %}

status/templates/update_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="yay">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" /> -->

    <title>
        {% block title %} Linked-Out - Status {% endblock %}
    </title>
</head>

<body>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

status/templates/update_status/update_status.html
{% extends "update_status/layout/base.html" %}

{% block content %}
<h1 class="main-title">Update Status</h1>
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'status:add_status' %}">
            <h2>Input Todo</h2>
            {% csrf_token %}
            {{ update_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
<section name="my-status" id="my-status">
    <div class="container">
        <!-- <h2 class="my-list-title">My List</h2> -->
        <div class="flex">
            {% if update_bar %}
                {% for data in update_bar %}
                    <div class="flex-item">
                        <div class="status">
                            <div class="status-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="status-description">
                                {{data.update}}
                            </div>
                            <!-- <div class="to-do-list-delete">
                                <div class="to-do-list-delete-button" data-id="{{data.id}}">Delete</div>
                            </div> -->
                        </div>
                    </div>
                {% endfor %}
            <!-- {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %} -->
        </div>
    </div>
</section>

{% endblock %}

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Tugas 1 PPW - LinkedOut">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block style %}
    <!-- styles goes here -->
    {% endblock %}
    <title>
        {% block title %}
          Linked-out
        {% endblock %}
    </title>
</head>
<body>

    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

</body>
</html>

templates/partials/footer.html
<p>Made with Love by {{author}}</p>

templates/partials/header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://linked-out.herokuapp.com/">Linked-Out</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/user_profile/">Profile</a></li>
        <li><a href="/status/">Status</a></li>
        <li><a href="/friend/">Add Friend</a></li>
        <li><a href="/dashboard/">Dashboard</a></li>
      </ul>
    </div>
  </div>
</nav>

user_profile/templates/user_profile.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block style %}
<!-- bootstrap csss -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_profile.css' %}" />
{% endblock %}
{% block title %}
User Profile by Kezia Irene
{% endblock %}
{% block content %}
<div class="Profile">
<h1>Profile</h1>
</div>
<hr/>

<section name="name">
    <p align = "center">
         <img src={{model_pic}} class="rounded-circle" widht="200" height="200">
    </p>  
    <p align = "center">
        <div class = "name"> 
        <h2 align="center">{{name}}</h2>
        </div>
    </p>  
</section>
<hr/>
<section name="about_me">
    <table class="table" align="center">
        <tr>
            <td>Birthday</td>
            <td>{{birthdate}}</td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>{{gender}}</td>
        </tr>
        <tr>
            <td>Expertise</td>
            <td>
                {% for data in expertise %}        
                    <span class="badge badge-pill badge-primary">{{data.expertise}}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{description}}</td>
        </tr>
    </table>
</section>
<hr/>


{% endblock %}